version: '3'
services:

  satosa-mongo:
    image: mongo
    container_name: satosa-mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: oidcop
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_DBUSER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_DBPASSWORD}"
    volumes:
      - mongodata:/data/db
      - /usr/share/zoneinfo/Europe/Rome:/etc/localtime:ro
      - ./mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    ports:
      - '27017-27019:27017-27019'

  satosa-mongo-express:
    image: mongo-express
    container_name: satosa-mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: satosauser
      ME_CONFIG_BASICAUTH_PASSWORD: satosapw
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_DBUSER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_DBPASSWORD}"
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_DBUSER}:${MONGO_DBPASSWORD}@satosa-mongo:27017/

  satosa-saml2spid:
    image: scolagreco/satosa-saml2spid
    container_name: satosa-saml2spid  
    depends_on:
      - satosa-mongo
    environment:
      - SATOSA_BY_DOCKER=1

      - SATOSA_BASE=https://$HOSTNAME
      # - SATOSA_CONTACT_PERSON_EMAIL_ADDRESS=support.example@organization.org
      # - SATOSA_CONTACT_PERSON_FISCALCODE=01234567890
      # - SATOSA_CONTACT_PERSON_GIVEN_NAME=Name
      # - SATOSA_CONTACT_PERSON_TELEPHONE_NUMBER=06123456789
      - SATOSA_DISCO_SRV=https://$HOSTNAME/static/disco.html
      # - SATOSA_ENCRYPTION_KEY=
      - MONGODB_PASSWORD=${MONGO_DBPASSWORD}
      - MONGODB_USERNAME=${MONGO_DBUSER}
      # - SATOSA_ORGANIZATION_DISPLAY_NAME_EN=Resource provided by Example Organization
      # - SATOSA_ORGANIZATION_DISPLAY_NAME_IT=Resource provided by Example Organization
      # - SATOSA_ORGANIZATION_NAME_EN=Resource provided by Example Organization
      # - SATOSA_ORGANIZATION_NAME_IT=Resource provided by Example Organization
      # - SATOSA_ORGANIZATION_URL_EN=https://example_organization.org
      # - SATOSA_ORGANIZATION_URL_IT=https://example_organization.org
      # - SATOSA_PRIVATE_KEYS=
      # - SATOSA_PUBLIC_KEY=
      # - SATOSA_SALT=
      # - SATOSA_STATE_ENCRYPTION_KEY
      # - SATOSA_UI_DESCRIPTION_EN=Resource description
      # - SATOSA_UI_DESCRIPTION_IT=Resource description
      # - SATOSA_UI_DISPLAY_NAME_EN=Resource Display Name
      # - SATOSA_UI_DISPLAY_NAME_IT=Resource Display Name
      # - SATOSA_UI_INFORMATION_URL_EN=https://example_organization.org/information_url_en
      # - SATOSA_UI_INFORMATION_URL_IT=https://example_organization.org/information_url_en
      # - SATOSA_UI_LOGO_HEIGHT=60
      # - SATOSA_UI_LOGO_URL=https://example_organization.org/logo.png
      # - SATOSA_UI_LOGO_WIDTH=80
      # - SATOSA_UI_PRIVACY_URL_EN=https://example_organization.org/privacy_en
      # - SATOSA_UI_PRIVACY_URL_IT=https://example_organization.org/privacy_en
      - SATOSA_UNKNOW_ERROR_REDIRECT_PAGE=https://$HOSTNAME/static/error_page.html
      # - SATOSA_USER_ID_HASH_SALT
    expose:
      - 10000
      - 9999
    ports:
      - "10000:10000"
      - "9999:9999"
    volumes:
       - /usr/share/zoneinfo/Europe/Rome:/etc/localtime:ro
       - satosa_metadata:/satosa_proxy/metadata
       - satosa_static:/satosa_proxy/static
       - satosa_certs:/satosa_proxy/pki

  satosa-nginx:
    image: nginx:alpine
    container_name: satosa-nginx
    depends_on:
      - satosa-saml2spid
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf_uwsgi_pass:/etc/nginx/nginx.conf:ro
      - ./nginx/50x.html:/usr/share/nginx/html/50x.html:ro
      - ./nginx/404.html:/usr/share/nginx/html/404.html:ro
      - ./nginx/403.html:/usr/share/nginx/html/403.html:ro
      - ./nginx/certs/:/etc/nginx/certs/:ro
      - satosa_static:/var/www/html

volumes:

  mongodata:
    external:
      name: satosa-saml2spid_mongodata

  nginx_certs:
    external:
      name: satosa-saml2spid_nginx_certs

  satosa_static:
    external:
      name: satosa-saml2spid_static        

  satosa_metadata:
    external:
      name: satosa-saml2spid_metadata

  satosa_certs:
    external:
      name: satosa-saml2spid_certs

#  nginx_conf:
#    driver_opts:
#      type: none
#      device: $PWD/nginx/
#      o: bind
